services:
  - type: web
    name: adaptive-liquidity-provision
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-render.txt || pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true --server.enableCORS=false --server.enableXsrfProtection=false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
    plan: free
